from datetime import datetime
from src.api import fetch_properties
from src.emailer import send_email
from src.hmlet_helpers import (
    get_connection,
    initialise_schema,
    insert_property_snapshot,
    get_last_two_property_snapshots,
    fetch_properties_for_snapshot,
    compare_property_snapshots,
    SUB_SEPARATOR,
)



# --------------------------------------------------
# OUTPUT
# --------------------------------------------------

def build_property_alert_message(new_properties, latest, latest_dt):
    lines = []
    lines.append("🗼🎉 New buildings opened in Tokyo!")
    lines.append(
        "These buildings have just opened! While there may not be availability for your dates yet, worth keeping an eye on!:\n"
    )
    lines.append(SUB_SEPARATOR)

    for pid in sorted(new_properties):
        p = latest[pid]

        lines.append(
            f"▪ [Property {p['property_id']}] "
            f"{p['property_name_en']} ({p['property_name_ja']})\n"
            f"  🏠 Rooms Available: {p['available_room_count']}\n"
            f"  💴 From ¥{p['minimum_list_price']:,}\n"
        )

    lines.append(SUB_SEPARATOR)
    lines.append(f"Snapshot taken at: {latest_dt}\n")
    lines.append("Generated by your friendly Hmlet unit availability bot 🤖\n")
    lines.append("Have a great day! 🌞\n")

    return "\n".join(lines)


# --------------------------------------------------
# MAIN
# --------------------------------------------------

def main():
    conn = get_connection()
    initialise_schema(conn)


    snapshot_dt = datetime.utcnow().isoformat()

    properties = fetch_properties()

    insert_property_snapshot(conn, snapshot_dt, properties)

    latest_dt, previous_dt = get_last_two_property_snapshots(conn)

    if not latest_dt or not previous_dt:
        print("Only one property snapshot exists — baseline established.")
        conn.close()
        return

    latest = fetch_properties_for_snapshot(conn, latest_dt)
    previous = fetch_properties_for_snapshot(conn, previous_dt)
    new_properties = compare_property_snapshots(latest, previous, latest_dt)

    if not new_properties:
        print("✅ No new properties detected.")
        conn.close()
        return

    message = build_property_alert_message(new_properties, latest)

    print(message)

    send_email(
        subject="✨ New Hmlet Properties!",
        body=message,
    )

    conn.close()


if __name__ == "__main__":
    main()
